### PR TITLE
Propose a new project structure and only export what should be publicly exposed

### PR DESCRIPTION
**Pull request by prologic**
Also makes this useable as an applet in my Go-based OS I'm working on 😅

### CODE REVIEW

**Comment by prologic** [comment]
@NicoNex Appreciate your input son this 😅 Is it too much? 🤔 😂

**Comment by NicoNex** [comment]
Hi @prologic, I'm not entirely convinced on the `func Main(stdout io.Writer, args []string) error` thing, but I like the idea of having `ExecFileVM`, `ExecFileEval`, `CompileFiles`, `VmREPL` and `EvalREPL` exported.
I was thinking: what if I make a different repo called maybe `tau-applet` or a new package called just `applet` inside tau repo with that exported `Main` that you need?

**Comment by prologic** [comment]
Nah it's okay I can drop that bit and move it to my project 👌

**Comment by NicoNex** [comment]
I think the REPL has been left out and by mistake you included a file called `.DS_Store`. 😄

**Comment by prologic** [comment]
In the end I changed my mind about exporting the REPL itself. Should we export it to? 🤔

**Comment by NicoNex** [comment]
I agree with the fact that having those functions exported is not of much use after all. 🤔 
Also remember to remove the `.DS_Store` file please.

**Pull request merged**
